name: Action Tester

on:
  workflow_dispatch:

jobs:
  github-action-notion-statusboard:
    runs-on: ubuntu-latest
    name: Test the Notion GitHub Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Notion
        uses: ./ # Uses an action in the root directory
        id: notion
        with:
          github-repository-query: user:Eomm is:public
          notion-token: ${{ secrets.NOTION_TOKEN }}
          database-id: ${{ secrets.NOTION_DATABASE_ID }}
